services:
  mongodb:
    image: mongo:8
    container_name: javify-mongodb
    restart: always
    environment:
      # Credenciais de acesso padrão (root)
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
