spring.application.name=javify-catalogo
server.port=8082

spring.mongodb.uri=mongodb://admin:adminpassword@localhost:27017/javify_db?authSource=admin

# spring.mongodb.host=localhost
# spring.mongodb.port=27017
# spring.mongodb.database=javify_db
# spring.mongodb.username=admin
# spring.mongodb.password=adminpassword
# spring.mongodb.authentication-database=admin

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG

# spring.data.redis.host=localhost
# spring.data.redis.port=6379
# spring.cache.type=redis
# spring.data.redis.timeout=2000ms
